services:
  - type: web
    name: surakshasetu-backend
    env: node
    rootDir: backend
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
